var zh={
  "edit":"編輯",
  "view":"檢視",
  "save":"存檔",
  "signup":"註冊",
  "login":"登入",
  "logout":"登出",
  "home":"首頁",
  "book":"書籍",
  "search":"搜尋",
  "# Error\nFile not found.\nYou may edit and save to create a new file !":"# 錯誤\n檔案不存在.\n你可以編輯後存檔以創建新檔案！",
  "Please login to save!":"請先登入後才能存檔！",
  "Save fail: You are not editor of the book !":"存檔失敗：你不是本書的編輯！",
  "Save Success!":"存檔成功",
  "Save Fail!":"存檔失敗",
  "Signup success!":"註冊成功",
  "Signup Fail: User name already taken by some others!":"註冊失敗:該名稱已被佔用！",
  "Login Success!":"登入成功！",
  "Login Fail!":"登入失敗！",
  "Logout Success!":"登出成功！",
  "Please login at first !":"請先登入！",
  "Create Book Success!":"創建書籍成功！",
  "Fail: Book already exist!":"登入失敗！",
}